---
abstract: 'A plugin for Nephia that give TOML responding feature'
author:
  - 'papix <mail@papix.net>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.5, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-Response-TOML
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Plugin::Response::TOML:
    file: lib/Nephia/Plugin/Response/TOML.pm
    version: 0.01
requires:
  Nephia: 0
  TOML: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/papix/Nephia-Plugin-Response-TOML/issues
  homepage: https://github.com/papix/Nephia-Plugin-Response-TOML
  repository: git://github.com/papix/Nephia-Plugin-Response-TOML.git
version: 0.01
